apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyspa.fullname" . }}-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.app.dbUser }}:{{ .Values.app.dbPassword }}@{{ .Values.app.dbHost }}:{{ .Values.app.dbPort }}/{{ .Values.app.dbName }}"
