apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyspa.fullname" . }}
  labels:
    {{- include "pyspa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pyspa.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
