apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "hello.fullname" . }}-test"
  labels:
    {{- include "hello.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.5.0
      command: ['sh', '-c']
      args:
        - |
          echo "Testing service...";
          curl -sS http://{{ include "hello.fullname" . }}:{{ .Values.service.port }} | head -n 5;
  restartPolicy: Never
